qt: playlistmedialist/TypeError: Cannot read property 'count' of null
When we click on Playlist view, a Qt warning is generated.
TypeError: Cannot read property 'count' of null

This is due to 'model.count' is called before function _getCount(model) is called

With this commit the warning is controlled.

Fixes: #28561